env:
  global:
    - CC_TEST_REPORTER_ID=26827ca98dd393967ae64c4fd543c121f84e3de0dff90a7f5327303fe558a274

language: java

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd m4e-webapp
  - mvn clean verify

jdk:
  - oraclejdk8

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
